KabulBlog/KabulBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    
    path('tinymce/',include('tinymce.urls'))

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

KabulBlog/blog/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .views import home,post,category,user_login,user_register,user_logout,addpost,add_category,update_category,deleteCategory
app_name = 'blog'
urlpatterns = [
   path('',home,name='home'),
   path('addpost/',addpost, name='addpost'),
   path('addcat/',add_category, name='addcat'),
   path('blog/<int:post_id>',post,name="blog"),
   path('category/<int:cat_id>',category, name="category"),
   path('update_category/<int:cat_id>',update_category, name="update_category"),
   path('delete_category/<int:cat_id>',deleteCategory, name="delete_category"),
   path('register',user_register,name='register'),
   path('login',user_login,name='login'),
   path('logout/',user_logout, name="logout"),

]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

KabulBlog/blog/models.py
from django.db import models
from django.utils.html import format_html
from tinymce.models import HTMLField
from datetime import datetime,date
# Create your models here.

# Category Model

class Category(models.Model):
    cat_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150)
    description = HTMLField()
    url = models.CharField(max_length=150)
    image = models.ImageField(upload_to='category/')
    added_date = models.DateTimeField(auto_now=True,null=True)


    # for showing the image in the admin view
    # def image_tag(self):
    #     return format_html('<img src = "/media{}"/ style = "width:40px;height:40px;border_radius:50%">'.format(self.image))
    def __str__(self):
        return self.title

# Post Model
class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    content = HTMLField()
    url = models.CharField(max_length=150)
    categ = models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post/')
    


    def __str__(self):
        return self.title

KabulBlog/blog/forms.py
from django import forms
from .models import Post,Category

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'



class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        

KabulBlog/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from blog.models import Post,Category
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .forms import PostForm,CategoryForm
# Create your views here.

def home(request):
    # Load all the post from db
    posts  = Post.objects.all()
    category = Category.objects.all()


    data = {
        'posts':posts,
        'cats': category
    }
    return render(request,'home.html', data)

def addpost(request):
    category = Category.objects.all()
    form = PostForm(request.POST, request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request,'Post has beed added successully')
            return redirect('blog:home')

        else:
            form = PostForm()
    
    # if request.method == 'POST':
    #     title = request.POST.get('title')
    #     content = request.POST.get('content')
    #     url = request.POST.get('url')
    #     categ = request.POST.get('categ')
    #     image = request.FILES.get('image')
    #     post = Post(title = title, 
    #         content = content,
    #         url = url,
    #         categ = categ,
    #         image = image
    #     )
    #     post.save()
    #     messages.success(request,'Post has beed added successully')
    #     return redirect('blog:home')
    return render(request, 'add_post.html', {'form':form,'category':category})

def post(request,post_id):
    post=Post.objects.get(post_id=post_id)
    category = Category.objects.all()
    context = {
        'post':post,
        'cats': category
    }
    return render(request,'posts.html',context)



def category(request,cat_id):
    categ = Category.objects.get(cat_id=cat_id)
    posts = Post.objects.filter(categ = categ)
    context = {
        'category': categ,
        'posts': posts
    }
    return render(request,'category.html',context)

def add_category(request):
    form = CategoryForm(request.POST,request.FILES)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request,'Post Added Successfully!')
            return redirect('blog:home')
        else:
            form = CategoryForm()
    return render(request,'add_category.html',{'form':form})

def update_category(request,cat_id):
    category = Category.objects.get(cat_id = cat_id)
    form = CategoryForm(request.POST or None,request.FILES, instance=category)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request,'Category update successfully')
            return redirect('blog:home')
        else:
            form = CategoryForm()
    return render(request,'update_category.html',{'form':form})
    

def deleteCategory(request,cat_id):
    category = Category.objects.get(cat_id = cat_id)
    category.delete()
    messages.success(request,"Category has been deleted")
    return redirect('blog:home')
    
def user_register(request):
    if request.method == 'POST':
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 != password2:
            messages.warning(request,"Password does not match")
            return redirect('blog:register')
        elif User.objects.filter(username=username).exists():
            messages.warning(request,"Username already taken")
            return redirect('blog:register')
        elif User.objects.filter(email=email).exists():
            messages.warning(request,"Email already taken")
            return redirect('blog:register')
        else:
            user = User.objects.create_user(
            first_name = firstname,
            last_name = lastname,
            username= username,
            email = email,
            password = password1,
            )
            user.save()
            messages.success(request,'User has been registered successully')
            return redirect('blog:login')
    return render(request,'register.html')
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request,username = username,password = password)
        # the fist username and password comming from the database
        if user is not None:
            login(request,user)
            return redirect('blog:home')
        else:
            messages.warning(request,"Invalid username or password")
            return redirect('blog:login')
    return render(request,'login.html')

def user_logout(request):
    logout(request)
    return redirect("blog:home")

KabulBlog/templates/add_category.html
{% extends 'base.html' %}
{%block title%}Add Post {%endblock title%}
{% block content %}
<div class="container">
    <h1 class="text-center">Add New Category</h1>
<div class="row z-depth-5">
    <form class="col s12" enctype="multipart/form-data" method = "POST">
      <div class="row">
        <div class="input-field col s12">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Post</button>

        </div>
      </div>
    </form>
  </div>
  </div>


{% endblock %}

KabulBlog/templates/add_post.html
{% extends 'base.html' %} 
{%block title%}Add Post {%endblock title%} 
{% block content %}
<div class="container">
    <h1 class="text-center">Add New Post</h1>
<div class="row z-depth-5">
    <form class="col s12" enctype="multipart/form-data" method = "POST">
      <div class="row">
        <div class="input-field col s12">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Post</button>
        </div>
      </div>
    </form>
  </div>
  </div>

<!-- <h2 class="center-align">Registration Form</h2>
<div class="container z-depth-5">
  <form action="{% url 'blog:addpost'%}" method="POST">
    {%csrf_token%}
    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" name="title" />
      </div>
      <div class="form-group col-md-12">
        <label for="content">Content</label>
        {% comment %} <input type="text" class="form-control" id="lastname" name="lastname"> {% endcomment %} 
        <textarea
          name="content"
          class="form-control"
          id="content"
          cols="30"
          rows="10"
        ></textarea>
      </div>
      <div class="form-group col-md-12">
        <label for="url">URL</label>
        <input type="text" class="form-control" id="url" name="url" />
      </div>
      <div class="form-group col-md-12">
        <label for="category">Category</label>
        <select name="category" id="category">
          {% for cat in category %}
          <option value="{{cat.title}}">{{cat.title}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group col-md-12">
        <label for="image">Image</label>
        <input type="file" class="form-control" id="image" name="image" />
      </div>
    </div>
    <button type="submit" class="btn btn-primary my-3">Sign in</button>
  </form>
</div> -->

{% endblock %}

KabulBlog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title%}{% endblock%}</title>
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Compiled and minified Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- Bootstrap CSS -->

</head>

<body>
    {%include 'header.html'%}
    {%block content%}
    {%endblock content%}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <script>
          M.toast({html: '    {{ message }}', class:'rounded'})
    
        </script>
      
        {% endfor %}
    </ul>
    {% endif %}
    <br><br><br>

    {%include 'footer.html'%}
    <script>
        M.AutoInit();
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $(".owl-carousel").owlCarousel(
                {
                    loop: true,
                    autoplay: true,
                    nav: true,
                    responsiveClass: true,
                    responsive: {
                        0: {
                            items: 1,
                            nav: true
                        },
                        600: {
                            items: 3,
                            nav: false
                        },
                        1000: {
                            items: 3,
                            nav: true,
                            loop: false
                        }
                    }
                }

            );
        });

    </script>
</body>

</html>


<style>
    .brand-logo {
        color: #fff;
        font-size: 2.5rem;
        font-weight:500;
    }

    .brand-logo:hover {
        color: white;
        text-decoration: none;
    }


    .btn:hover {
        color: white;
    }

    .nav-item {
        font-size: 1rem;
        
    }
</style>

KabulBlog/templates/category.html
{% extends 'base.html' %}

{%block title%}Category{%endblock title%}

{% block content %}
 <div class="container-custom">
      <h3>{{category.title}}</h3>
      <div class="img-container">
           <img src="/media/{{category.image}}" class="responsive-img cat-img" width="250px" hieght="250px" alt="">
           
      </div>
      <div class="collection">
           {%for p in posts%}
               <a href="/blog/{{p.url}}" class="collection-item">{{p.title}}</a>
          {%empty%}
          <h3>No Post in this category</h3>
          {%endfor%}
          
        </divl>
 </div>
{% endblock content %}

KabulBlog/templates/footer.html
<footer class="page-footer" style="background-color: #343a40;">
    <div class="container">
      {% comment %} <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Kabul Blog</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Contact Us</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="web"></a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div> {% endcomment %}
      <div class="w3-center w3-small w3-opacity center-align">
        W3Schools is optimized for learning and training. Examples might be simplified to improve reading and learning.
        Tutorials, references, and examples are constantly reviewed to avoid errors, but we cannot warrant full correctness of all content.
        While using W3Schools, you agree to have read and accepted our <a href="/about/about_copyright.asp">terms of use</a>, 
        <a href="/about/about_privacy.asp">cookie and privacy policy</a>.<br><br>
        <a href="/about/about_copyright.asp">Copyright 1999-2022</a> by Refsnes Data. All Rights Reserved.<br>
        <a href="//www.w3schools.com/w3css/default.asp">W3Schools is Powered by W3.CSS</a>.<br><br>
        </div>
    </div>
  </footer>

KabulBlog/templates/header.html
<!-- Dropdown Structure -->
<div class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
  <a href="{% url 'blog:home'%}" class="brand-logo">Kabul Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"><span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active"><a href="{% url 'blog:home'%}" class="nav-link">Home</a></li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown">Category</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {%for cat in cats%}
          <a class="dropdown-item" href="{% url 'blog:category' cat.cat_id %}">{{cat.title}}</a>
          {%endfor%}
        </div>
      </li>
      {% if user.is_authenticated%}
      <li>
        <li class="nav-item"><a href="{% url 'blog:home'%}" class="nav-link">{{request.user}}</a></li>
        <li class="nav-item"><a href="{% url 'blog:addpost'%}" class="nav-link">Add Post</a></li>
        <li class="nav-item"><a href="{% url 'blog:addcat'%}" class="nav-link">Add Category</a></li>
      </li>
      <li class="nav-item"><a href="{% url 'blog:logout'%}" class="nav-link">Logout</a></li>
      {% else %}
      <li class="nav-item"><a href="{% url 'blog:register'%}" class="nav-link">Register</a></li>
      <li class="nav-item"><a href="{% url 'blog:login'%}" class="nav-link">Login</a></li>
      <li class="nav-item"><a href="/admin" class="nav-link">Admin Login</a></li>
      {%endif%}
    </ul>
  </div>
</div>
</div>


 

KabulBlog/templates/home.html
{% extends 'base.html' %}
{%block title%}Welcome to Kabul Blog {%endblock title%}

{% block content %}

<div class="container">
    <!-- Set up your HTML -->
<div class="owl-carousel">
   
    {%for cat in cats%}

        <div class="card item">
            <div class="img-container">
                <img src="/media/{{cat.image}}"  height="150px" alt="">
            </div>
            <div class="card-content">
                <div class="card-title">
                    {{cat.title}}
                    <br>
                    {{cat.added_date}}
                </div>
                <p class="truncate">{{cat.description|safe}}</p>
                <div class="container center-align" style="position: absolute; top: 80%;">
                    <a href="{% url 'blog:category' cat.cat_id %}" class="btn">View</a>
                    <a href="{% url 'blog:update_category' cat.cat_id %}" class="btn">Update</a>
                    <a href="{% url 'blog:delete_category' cat.cat_id %}"  class="btn" onclick="return confirm('Are you sure about this ?')" >Delete</a>
                </div>
            </div>
        </div>
    {%endfor%}
  </div>
</div> 

<div class="container my-10">
    <div class="row">    
        <div class="col s12">
            
            {% for p in posts %}
            
            <h2>{{p.title}}</h2>
            {{p.content |truncatewords:55| safe}}
            <div class="row">
                <div class="col s12 m8">

                    
                    <div class="mt20">
                        <a href="{% url 'blog:blog' p.post_id %}" class="btn btn-primary">Read More</a>
                    </div>
                </div>
                {% if p.image %}
                <div class="col s12 m4">
                    <img src="/post/{{p.image}}" alt="" class="responsive-img">
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock content %}

KabulBlog/templates/login.html
{% extends 'base.html' %}
{% block title %}
<title>Login Page</title>
{% endblock title %}

{%block content%}
{%for message in messages%}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong>Message: </strong>{{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<h2 class="center-align">Login Form</h2>
<div class="container">

    <form action="{% url 'blog:login'%}" method="POST">
        {%csrf_token%}
        
        <div class="form-row">
        <div class="form-group col-md-12">
            <label for="inputusername">Username</label>
            <input type="text" class="form-control" id="username" placeholder="Username" name="username">
        </div>
        
            <div class="form-group col-md-12">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
        </div>
        <button type="submit" class="btn btn-primary my-3">Login</button>
    </form>
</div>
{%endblock content%}

KabulBlog/templates/posts.html
{% extends 'base.html'%}
{%block title%} Post {%endblock title%}
{%block content%}
<div class="container-custom">
    <div class="row">
        <div class="col-9 s12 m10">
            <h3>{{post.title}}</h3>
            <p>{{post.categ.title}}</p>
            <img src="/media/{{post.image}}" class="responsive-img" alt="">
            <br>
            <p>
                {{post.content|safe}}
            </p>
        </div>
        <div class="col-3 s12 m2 sidebar">
            {%for cat in cats%}

            <div class="card item">
                <div class="img-container">
                    <img src="/media/{{cat.image}}" class="" width="50px" hieght = "50px" alt="">
                </div>
                <div class="card-content">
                    <b>
                        {{cat.title}}
                    </b>
                    <p class="truncate">{{cat.description|safe}}</p>
                    <div class="container center-align mt20">
                        <a href="/category/{{cat.url}}" class="btn">View</a>
                    </div>
                </div>
            </div>
        {%endfor%}
        </div>
    </div>
</div>
{%endblock content%}

KabulBlog/templates/register.html
{% extends 'base.html' %}
{% block title %}
<title>Register Page</title>
{% endblock title %}

{%block content%}
{%for message in messages%}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong>Message: </strong>{{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endfor %}
<h2 class="center-align">Registration Form</h2>
<div class="container">

    <form action="{% url 'blog:register'%}" method="POST">
        {%csrf_token%}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputfirstname">First Name</label>
                <input type="text" class="form-control" id="firstname" name="firstname">
            </div>
            <div class="form-group col-md-6">
                <label for="inputlastname">Last Name</label>
                <input type="text" class="form-control" id="lastname" name="lastname">
            </div>
        {% comment %} </div> {% endcomment %}
        <div class="form-group col-md-12">
            <label for="inputusername">Username</label>
            <input type="text" class="form-control" id="username" placeholder="Username" name="username">
        </div>
        <div class="form-group col-md-12">
            <label for="inputemail">Email</label>
            <input type="email" class="form-control" placeholder="Email" id="email" name="email">
        </div>
        {% comment %} <div class="form-row"> {% endcomment %}
            <div class="form-group col-md-6">
                <label for="inputpassword1">Password 1</label>
                <input type="password" class="form-control" id="password1" name="password1">
            </div>
            <div class="form-group col-md-6">
                <label for="inputpassword2">Password 2</label>
                <input type="password" class="form-control" id="password2" name="password2">
            {% comment %} </div> {% endcomment %}

        </div>
        </div>
        <button type="submit" class="btn btn-primary my-3">Sign in</button>
    </form>
</div>

{%endblock content%}

KabulBlog/templates/update_category.html
{% extends 'base.html' %}
{%block title%}Update Category {%endblock title%}
{% block content %}
<div class="container">
    <h1 class="text-center">Update Category</h1>
<div class="row z-depth-5">
    <form class="col s12" enctype="multipart/form-data" method = "POST">
      <div class="row">
        <div class="input-field col s12">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update Category</button>

        </div>
      </div>
    </form>
  </div>
  </div>


{% endblock %}